[package]
name = "tinydraw"
version = "0.1.1"
authors = ["Antonio Mamić <mmima191@gmail.com>"]
edition = "2021"
description = "A small library for 2D drawing in Rust"
readme = "README.md"
repository = "https://github.com/DarkLord76865/tinydraw-rs"
license = "MIT"
keywords = ["2d", "drawing", "graphics", "rendering", "images"]
categories = ["graphics", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.7"
bytemuck = "1.13.0"
